export type ClusterDef = {
  id: number;
  label: string;
  cx: number;
  cy: number;
  spread: number;
  jobZoneRange: [number, number];
  wageRange: [number, number];
  titles: string[];
  skills: string[];
  blurb: (title: string) => string;
};

export const CLUSTERS: ClusterDef[] = [
  {
    id: 0,
    label: "Healthcare",
    cx: 200,
    cy: 240,
    spread: 75,
    jobZoneRange: [3, 4],
    wageRange: [55000, 220000],
    titles: [
      "Registered Nurses",
      "Family Physicians",
      "Surgeons",
      "Physical Therapists",
      "Pharmacists",
      "Nurse Practitioners",
      "Anesthesiologists",
      "Physician Assistants",
      "Radiologic Technologists",
      "Respiratory Therapists",
      "Occupational Therapists",
      "Dental Hygienists",
      "Diagnostic Medical Sonographers",
      "Speech-Language Pathologists",
      "Clinical Psychologists",
      "Cardiologists",
    ],
    skills: [
      "Patient Assessment",
      "Clinical Reasoning",
      "Active Listening",
      "Critical Thinking",
      "Pharmacology",
      "Medical Documentation",
      "Empathy",
      "Anatomy",
      "Decision Making",
      "Sterile Technique",
    ],
    blurb: (t) =>
      `${t} diagnose, treat, and care for patients across clinical settings, balancing technical precision with sustained interpersonal attention.`,
  },
  {
    id: 1,
    label: "Knowledge Work",
    cx: 510,
    cy: 180,
    spread: 80,
    jobZoneRange: [3, 4],
    wageRange: [70000, 240000],
    titles: [
      "Software Developers",
      "Data Scientists",
      "Machine Learning Engineers",
      "Product Managers",
      "Management Consultants",
      "Financial Analysts",
      "Actuaries",
      "Lawyers",
      "Economists",
      "Research Scientists",
      "UX Researchers",
      "Statisticians",
      "Quantitative Analysts",
      "Strategy Consultants",
      "Investment Bankers",
      "Patent Attorneys",
    ],
    skills: [
      "Analytical Thinking",
      "Problem Solving",
      "Written Communication",
      "Programming",
      "Statistics",
      "Research",
      "Modeling",
      "Stakeholder Management",
      "SQL",
      "Systems Thinking",
    ],
    blurb: (t) =>
      `${t} apply structured analysis and abstract reasoning to ambiguous problems, often working through written artifacts and quantitative models.`,
  },
  {
    id: 2,
    label: "Skilled Trades",
    cx: 820,
    cy: 320,
    spread: 80,
    jobZoneRange: [2, 3],
    wageRange: [42000, 110000],
    titles: [
      "Electricians",
      "Plumbers",
      "HVAC Technicians",
      "Carpenters",
      "Welders",
      "Industrial Machinery Mechanics",
      "Diesel Mechanics",
      "Pipefitters",
      "Sheet Metal Workers",
      "Millwrights",
      "Boilermakers",
      "Elevator Installers",
      "Stationary Engineers",
      "Glaziers",
      "Ironworkers",
    ],
    skills: [
      "Manual Dexterity",
      "Equipment Maintenance",
      "Troubleshooting",
      "Blueprint Reading",
      "Spatial Reasoning",
      "Safety Compliance",
      "Tool Use",
      "Problem Solving",
      "Mechanical Knowledge",
    ],
    blurb: (t) =>
      `${t} install, maintain, and repair the physical infrastructure that everything else depends on, working with hands and tools at job sites.`,
  },
  {
    id: 3,
    label: "Care Work",
    cx: 160,
    cy: 540,
    spread: 65,
    jobZoneRange: [1, 2],
    wageRange: [28000, 52000],
    titles: [
      "Home Health Aides",
      "Nursing Assistants",
      "Childcare Workers",
      "Personal Care Aides",
      "Preschool Teachers",
      "Social and Human Service Assistants",
      "Medical Assistants",
      "Direct Support Professionals",
      "Hospice Aides",
      "Recreation Workers",
      "Community Health Workers",
      "School Aides",
    ],
    skills: [
      "Patience",
      "Empathy",
      "Active Listening",
      "Daily Living Support",
      "Observation",
      "De-escalation",
      "Reliability",
      "Communication",
    ],
    blurb: (t) =>
      `${t} provide hands-on physical and emotional support to people who need help with the activities of daily life, often under demanding conditions.`,
  },
  {
    id: 4,
    label: "Creative",
    cx: 460,
    cy: 580,
    spread: 70,
    jobZoneRange: [2, 4],
    wageRange: [38000, 160000],
    titles: [
      "Graphic Designers",
      "Writers and Authors",
      "Film and Video Editors",
      "Photographers",
      "Art Directors",
      "Interior Designers",
      "Architects",
      "Industrial Designers",
      "Animators",
      "Music Composers",
      "Producers and Directors",
      "Illustrators",
      "Creative Directors",
      "Sound Engineers",
    ],
    skills: [
      "Visual Composition",
      "Creativity",
      "Aesthetic Judgment",
      "Storytelling",
      "Adobe Suite",
      "Concept Development",
      "Typography",
      "Color Theory",
      "Iteration",
    ],
    blurb: (t) =>
      `${t} translate ideas into expressive artifacts — image, sound, narrative, space — through repeated cycles of making, critiquing, and refining.`,
  },
  {
    id: 5,
    label: "Sales / Service",
    cx: 760,
    cy: 620,
    spread: 70,
    jobZoneRange: [1, 3],
    wageRange: [32000, 130000],
    titles: [
      "Retail Salespersons",
      "Cashiers",
      "Insurance Sales Agents",
      "Real Estate Brokers",
      "Sales Representatives, Wholesale",
      "Customer Service Representatives",
      "Account Managers",
      "Telemarketers",
      "Travel Agents",
      "Financial Services Sales Agents",
      "Enterprise Sales Reps",
    ],
    skills: [
      "Persuasion",
      "Active Listening",
      "Negotiation",
      "Product Knowledge",
      "Service Orientation",
      "Resilience",
      "Communication",
      "Pipeline Management",
    ],
    blurb: (t) =>
      `${t} build trust with customers, match products to needs, and close transactions, often working under quota pressure or commission.`,
  },
  {
    id: 6,
    label: "Operations",
    cx: 320,
    cy: 760,
    spread: 75,
    jobZoneRange: [2, 4],
    wageRange: [45000, 170000],
    titles: [
      "Logistics Managers",
      "Supply Chain Analysts",
      "Operations Managers",
      "Warehouse Supervisors",
      "Industrial Engineers",
      "Procurement Specialists",
      "Quality Assurance Managers",
      "Production Planners",
      "Distribution Managers",
      "Inventory Analysts",
      "Plant Managers",
      "Process Improvement Specialists",
    ],
    skills: [
      "Process Optimization",
      "Coordination",
      "Data Analysis",
      "Vendor Management",
      "Project Management",
      "Forecasting",
      "Lean Methodology",
      "Decision Making",
    ],
    blurb: (t) =>
      `${t} keep complex flows of material, people, and information moving on time and on budget across multiple sites and stakeholders.`,
  },
  {
    id: 7,
    label: "Engineering",
    cx: 660,
    cy: 800,
    spread: 75,
    jobZoneRange: [4, 4],
    wageRange: [80000, 200000],
    titles: [
      "Mechanical Engineers",
      "Electrical Engineers",
      "Civil Engineers",
      "Aerospace Engineers",
      "Chemical Engineers",
      "Materials Engineers",
      "Robotics Engineers",
      "Biomedical Engineers",
      "Structural Engineers",
      "Petroleum Engineers",
      "Nuclear Engineers",
      "Environmental Engineers",
    ],
    skills: [
      "Mathematical Modeling",
      "CAD",
      "Physics",
      "Systems Design",
      "Technical Writing",
      "Simulation",
      "Project Management",
      "Materials Science",
      "Problem Solving",
    ],
    blurb: (t) =>
      `${t} design, analyze, and validate physical systems against rigorous performance, safety, and cost constraints, working across disciplines.`,
  },
  {
    id: 8,
    label: "Education",
    cx: 850,
    cy: 80,
    spread: 65,
    jobZoneRange: [3, 4],
    wageRange: [42000, 130000],
    titles: [
      "Elementary School Teachers",
      "High School Teachers",
      "Postsecondary Teachers",
      "Special Education Teachers",
      "Instructional Coordinators",
      "School Counselors",
      "Librarians",
      "Adult Literacy Teachers",
      "Education Administrators",
      "Curriculum Designers",
      "Math Teachers",
    ],
    skills: [
      "Instruction",
      "Classroom Management",
      "Lesson Planning",
      "Assessment",
      "Patience",
      "Verbal Communication",
      "Subject Expertise",
      "Differentiation",
    ],
    blurb: (t) =>
      `${t} design and deliver learning experiences that move people from where they are to where they want to go, across vastly different starting points.`,
  },
  {
    id: 9,
    label: "Hospitality",
    cx: 80,
    cy: 80,
    spread: 60,
    jobZoneRange: [1, 3],
    wageRange: [30000, 95000],
    titles: [
      "Chefs and Head Cooks",
      "Restaurant Managers",
      "Hotel Managers",
      "Bartenders",
      "Sommeliers",
      "Event Planners",
      "Concierges",
      "Pastry Chefs",
      "Food Service Managers",
      "Catering Directors",
      "Sous Chefs",
    ],
    skills: [
      "Service Orientation",
      "Time Management",
      "Composure Under Pressure",
      "Coordination",
      "Hospitality",
      "Menu Knowledge",
      "Aesthetic Judgment",
      "Communication",
    ],
    blurb: (t) =>
      `${t} orchestrate the moments around food, drink, and stay — turning logistics, taste, and timing into experiences guests remember.`,
  },
];
